AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ClassLength:
  Max: 200

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
